// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSUCLAFuR9xT5T4wtEJQSAF5oUeYQcZNs',
    appId: '1:346891414464:web:5411660af5734edb987625',
    messagingSenderId: '346891414464',
    projectId: 'mynotes-flutter-backend-app',
    authDomain: 'mynotes-flutter-backend-app.firebaseapp.com',
    storageBucket: 'mynotes-flutter-backend-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRMR94YlzwlleFthyg5jvjj2_r_GyBx2I',
    appId: '1:346891414464:android:90b5b3adb7ca622f987625',
    messagingSenderId: '346891414464',
    projectId: 'mynotes-flutter-backend-app',
    storageBucket: 'mynotes-flutter-backend-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGI9q3NyFpL0wlwj48qwDFPZXAP-BWeBw',
    appId: '1:346891414464:ios:b787025dea407d01987625',
    messagingSenderId: '346891414464',
    projectId: 'mynotes-flutter-backend-app',
    storageBucket: 'mynotes-flutter-backend-app.appspot.com',
    iosBundleId: 'com.flutterstart.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGI9q3NyFpL0wlwj48qwDFPZXAP-BWeBw',
    appId: '1:346891414464:ios:12ae22a7c7262901987625',
    messagingSenderId: '346891414464',
    projectId: 'mynotes-flutter-backend-app',
    storageBucket: 'mynotes-flutter-backend-app.appspot.com',
    iosBundleId: 'com.flutterstart.mynotes.RunnerTests',
  );
}
